name: Python Linting

on:
  pull_request:
    paths:
      - '**.py'  # Runs only on Python files

jobs:
  lint:
    runs-on: ubuntu-latest  # Runs on an Ubuntu VM
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Match the version you're using locally

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      
      - name: Run Pylint
        run: |
          pylint sample.py  # Or use your actual entry point file here
