name: Python Linting

on:
  pull_request:
    paths:
      - '**.py'  # Runs only on Python files
    branches:
      - main  # Or your branch name
  push:
    branches:
      - main  # Or your branch name

jobs:
  lint:
    runs-on: ubuntu-latest  # Runs on an Ubuntu VM
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Match the version you're using locally

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Debug: List Python Files
        run: |
          echo "Listing Python files..."
          git ls-files '*.py'
      
      - name: Run Pylint on All Files
        run: |
          pylint $(git ls-files '*.py') --output-format=parseable | tee pylint-report.txt

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: pylint-report.txt

      - name: Run Pylint with GitHub Annotations
        run: |
          pylint $(git ls-files '*.py') --output-format=json > pylint.json
          python convert_pylint_to_annotations.py


      - name: Debug Pylint Output
        run: |
          pylint $(git ls-files '*.py') --output-format=parseable | tee pylint-report.txt

